services:
  - type: web
    name: strapi
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    nodeVersion: 18.17.0
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NODE_ENV
        value: production
      - key: DATABASE_HOST
        value: aws-0-ap-southeast-1.pooler.supabase.com
      - key: DATABASE_PORT
        value: 6543
      - key: DATABASE_NAME
        value: postgres
      - key: DATABASE_USERNAME
        value: postgres.awblduzgygxcktsohjbk
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 1337